src/Service/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Service.Models;

namespace Service.Controllers
{
    [AllowAnonymous]
    public class HomeController : Controller
    {
        public HomeController()
        {
        }

        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
                return IndexWhenAuthenticated();

            return View("Index");
        }

        public ActionResult IndexWhenAuthenticated()
        {
            return View("IndexWhenAuthenticated");
        }

        public ActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Service/Controllers/SignUpController.cs
using System;
using System.Security.Claims;
using System.Threading.Tasks;
using Common.Models;
using Common.Models.Identity;
using Common.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Service.Controllers
{
    [AllowAnonymous]
    public class SignUpController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;

        public SignUpController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _userManager = userManager ?? throw new NullReferenceException();
            _signInManager = signInManager ?? throw new NullReferenceException();
        }

        [Route("signup")]
        public ActionResult SignUpForm()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> SignUpUser(SignUpViewModel user)
        {
            if (ModelState.IsValid)
            {
                var appUser = new AppUser
                {
                    UserName = user.Email,
                    Email = user.Email,
                };

                var result = await _userManager.CreateAsync(appUser, user.Password);
                if (result.Succeeded)
                {
                    // **Uncomment this line of code when you want to generate an new claim(type Role) to a user. Then, run the Application and SignUp.**
                    //await _userManager.AddClaimAsync(appUser, new Claim(ClaimTypes.Role, RoleName.Admin));

                    await _signInManager.SignInAsync(appUser, isPersistent: false);
                    return RedirectToAction("IndexWhenAuthenticated", "Home");
                }

                foreach (var identityError in result.Errors)
                {
                    ModelState.AddModelError(identityError.Code, identityError.Description);
                }
            }

            return View(user);
        }

    }
}

src/Service/Views/Home/Index.cshtml
@{
    ViewBag.Title = "ViFlix";
}

@{
    Layout = "";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <environment include="Staging,Production,Development">
        <link rel="stylesheet" href="~/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/bootstrap-flatly.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <script src="~/js/modernizr-2.6.2.js"></script>
    </environment>
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ViFlix", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Login", "LoginForm", "Login", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Sign Up", "SignUpForm", "SignUp", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>

    <div class="container body-content">
        <div class="jumbotron">
            <h1>ViFlix</h1>
            <p class="lead">WATCH ANYWHERE. CANCEL ANYTIME.</p>
        </div>
    </div>

</body>
</html>

src/Service/Views/Home/IndexWhenAuthenticated.cshtml
@{
    ViewBag.Title = "ViFlix";
}

<div class="container body-content">
    <div class="jumbotron">
        <h1>ViFlix</h1>
        <p class="lead">WATCH ANYWHERE. CANCEL ANYTIME.</p>
    </div>
</div>