src/Service/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using Common.Models.Identity;
using Common.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Service.Controllers
{
    [AllowAnonymous]
    public class LoginController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;

        public LoginController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
            _signInManager = signInManager ?? throw new ArgumentNullException(nameof(signInManager));
        }

        [Route("login")]
        public ActionResult LoginForm()
        {
            return View();
        }

        public async Task<ActionResult> LoginUser(LoginViewModel user)
        {
            if (ModelState.IsValid)
            {
                var appUser = await _userManager.FindByEmailAsync(user.Email);
                if (appUser != null && await _userManager.CheckPasswordAsync(appUser, user.Password))
                {
                    await _signInManager.SignInAsync(appUser, isPersistent: false);
                    return RedirectToAction("Index", "Home");
                }
            }
            ModelState.AddModelError("", @"Invalid username or password");

            return View(user);
        }

        public async Task<ActionResult> LogOut()
        {
            await _signInManager.SignOutAsync();

            return RedirectToAction("Index", "Home");
        }
    }
}

src/Service/Controllers/RentalsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Service.Controllers
{
    public class RentalsController : Controller
    {
        [Route("rentals/new")]
        public ActionResult RentalForm()
        {
            return View();
        }
    }
}

src/Service/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <environment include="Staging,Production,Development">
        <link rel="stylesheet" href="~/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/bootstrap-flatly.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/toastr.css" />
        <script src="~/js/modernizr-2.6.2.js"></script>
    </environment>
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
</head>
<body>
    <partial name="_NavBar" />
    @*@Html.Partial("_NavBar")*@
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ViFlix ....such an experience!</p>
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/toastr")*@
    @*@RenderSection("scripts", required: false)*@
</body>
</html>

src/Service/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("ViFlix", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("New Rental", "RentalForm", "Rentals")</li>
                <li>@Html.ActionLink("Customers", "GetCustomers", "Customers")</li>
                <li>@Html.ActionLink("Movies", "GetMovies", "Movies")</li>
                <li>@Html.ActionLink("Sign Out", "LogOut", "Login")</li>
            </ul>
        </div>
        <div class="alert-success checkbox-inline">
            Hello @User.Identity.Name
        </div>
    </div>
</div>